services:
  postgres:
    image: postgres:16
    container_name: pinflag-postgres

    environment:
      POSTGRES_DB: pinflag
      POSTGRES_USER: pinflag
      POSTGRES_PASSWORD: pinflag

    ports:
    - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data: